### ISSUE TITLE
Appreciation, forked into neotest-vitest

### ISSUE THREAD

**Issue by KaiSpencer** [haydenmeade/neotest-jest#1]
Hey @haydenmeade,

Just like to say good work on this, just letting you know I have forked this and made some modifications to work with Vitest

https://github.com/KaiSpencer/neotest-vitest

Maybe down the line we could coalesce these two into one plugin with some configuration options since the actual code is so similar :)

**Comment by haydenmeade** [comment]
Awesome! Sounds great

**Comment by haydenmeade** [comment]
Not sure how we can communicate on improvements, but just made a commit for test/it alias in the treesitter query. I'm not familiar with vitest vs jest. What are the main changes in vitest adaptor if we are thinking of refactoring?

**Comment by KaiSpencer** [comment]
> 

Not sure on communication either! :D 

There isnt much changed, the command and args are slightly different. 
And the json output is very slightly different also, a couple of keys aren't in the vitest json so I had to work round them. 

So really, the only thing that will need implementing is a couple of instances where we need to parse the json slightly differently.
