### ISSUE TITLE
Add escape characters to the regex on filter by test name

### ISSUE THREAD

**Issue by marilari88** [haydenmeade/neotest-jest#11]
When I try to run a single test containing special chars in its name (eg. parenthesis), it doesn't run. I think that text without escaping chars applied to filter option don't match the test name

**Comment by adrigzr** [comment]
Hi @marilari88,

I don't see the problem with the adapter. I think it is a problem with the `neojest` framework. Do you mind opening an issue there?

**Comment by marilari88** [comment]
Hi @adrigzr, the problem is related to Jest cli command. I opened a PR with a fix
