### ISSUE TITLE
No Tests Found in NX monorepo

### ISSUE THREAD

**Issue by dlip** [haydenmeade/neotest-jest#13]
I'm trying to run tests in an NX monorepo, it works with neotest-vim-test but not with this package

**Comment by aaronmcadam** [comment]
I'm having trouble with an Nx project too. We need to be able to overwrite the location of the Jest config file, as mentioned in #14.

**Comment by haydenmeade** [comment]
Let me know if latest version with config override fixes this issue. Otherwise an example file / repo would help.

**Comment by aaronmcadam** [comment]
@haydenmeade thanks, this is progress! I get more accurate test reporting in the buffer and the summary.

But now I don't see a readable output (for `require("neotest").output.open()`), I see JSON instead:
<img width="791" alt="CleanShot 2022-07-11 at 12 45 59@2x" src="https://user-images.githubusercontent.com/37928/178258037-da68ef20-8d44-4cec-b6ae-2a7b067b7ddd.png">

**Comment by aaronmcadam** [comment]
@haydenmeade If you'd like to test against an Nx project, here's one of my projects using it: https://github.com/aaronmcadam/cat-match

**Comment by haydenmeade** [comment]
I improved the output to point to the console output, seems to be working for me with no overrides. 
![image](https://user-images.githubusercontent.com/5895445/178368614-d715c44e-6ca6-4b4e-add1-01f5131a40d5.png)

**Comment by aaronmcadam** [comment]
Nice! thanks so much @haydenmeade! I've confirmed it works with no extra config at all! ❤️
