### ISSUE TITLE
Why neotest-jest needs lsconfig, `module 'lspconfig' not found`

### ISSUE THREAD

**Issue by MuhammadSawalhy** [haydenmeade/neotest-jest#24]
I'm still using **coc.vim** language server but planning to migrate to the native NeoVim language server inshallah.
Why do we need **lsconfig** to be able to use this plugin?!

![image](https://user-images.githubusercontent.com/42011920/179395385-f374a01b-bdf8-48bf-8a1d-f03d784d5f8d.png)

**Comment by haydenmeade** [comment]
Fixed, we were using some utils from lsp-config
