### ISSUE TITLE
Support running tests written in Typescript

### ISSUE THREAD

**Issue by BojanStipic** [haydenmeade/neotest-jest#3]
It seems that this plugin is running `node_modules/.bin/jest` directly and then it fails if test files are written in Typrscript. Consider running `npm test --` instead as that script is usually configured correctly to do all the preprocessing required.

This should also probably be configurable, in case the test script is named differently for some projects.

Thanks for the plugin!

**Comment by haydenmeade** [comment]
Thanks for the find, I have a jest config file to run typescript so that's why I was missing this. Best option I think is to have a customisable run command, I'll have a look into it

**Comment by haydenmeade** [comment]
You should be able to override the command in the latest version:
```
require('neotest-jest')({
          jestCommand = "npm test --"
        })
```
Let me know if that works!

**Comment by BojanStipic** [comment]
Thank you very much, that works great!
