### ISSUE TITLE
Accessing the logs of the logger

### ISSUE THREAD

**Issue by primeapple** [haydenmeade/neotest-jest#4]
Thanks for this awesome plugin.
I have troubles using it, probably because of the wrong `jestCommand`. So I would like to debug, and you already added some log calls that maybe catch my problem.
However, I don't know how to access these logs? Could you help me out with this?

**Comment by adrigzr** [comment]
This is a little tricky... for me it is in: `~/.local/state/nvim/neotest.log`.

**Comment by haydenmeade** [comment]
You can always add some print calls if all else fails, feel free to reopen if it's still occurring
