### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'run' (a nil value)

### ISSUE THREAD

**Issue by sjdonado** [haydenmeade/neotest-jest#48]
Not sure what is causing this error. But I cannot run any of the `nvim-neotest` commands

- `require("neotest").run.run()`
```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'run' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```
- `require("neotest").run.run(vim.fn.expand("%"))`
```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'run' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```
I followed the packer setup recommended in the README.md:
```
use({
  'nvim-neotest/neotest',
  requires = {
    ...,
    'haydenmeade/neotest-jest',
  }
  config = function()
    require('neotest').setup({
      ...,
      adapters = {
        require('neotest-jest')({
          jestCommand = "npm test --",
          jestConfigFile = "custom.jest.config.ts",
          env = { CI = true },
          cwd = function(path)
            return vim.fn.getcwd()
          end,
        }),
      }
    })
  end
})
```
And I have `dap-vscode-js` configured https://github.com/sjdonado/sjdonado.nvim/blob/master/lua/sjdonado/debugger/node.lua

**Comment by cw0** [comment]
In my case, the config function in packer wasn't running. I called it explicitly elsewhere and the errors went away.

**Comment by sjdonado** [comment]
> In my case, the config function in packer wasn't running. I called it explicitly elsewhere and the errors went away.

how you did it?

**Comment by cw0** [comment]
I called the following snippet outside of packer's startup function.
```lua
require('neotest').setup({
    adapters = {
		require("neotest-jest"),
	},
	output = {
		enable = true,
		open_on_run = true,
	},
})
```
The section in my packer startup function looks like this now:
```lua
  use {
    "nvim-neotest/neotest",
    requires = {
      'nvim-lua/plenary.nvim',
      'nvim-treesitter/nvim-treesitter',
      'antoinemadec/FixCursorHold.nvim',
      'haydenmeade/neotest-jest'
    },
  }
```

**Comment by Rimann91** [comment]
Had the exact same issue with the lazy.nvim manager, I wonder if this can be fixed or if there is a better solution?
