### ISSUE TITLE
Output does not work

### ISSUE THREAD

**Issue by dahmc** [haydenmeade/neotest-jest#6]
`lua require("neotest").output.open({ enter = true })` after running a test does not seem to work

<img width="460" alt="175230566-32e7f6cc-a41c-4da8-ab4f-815378cfa969" src="https://user-images.githubusercontent.com/75008413/175267034-9d6300bb-e07a-4673-9873-2d3837d2544d.png">

It works with the `neotest-vim-test` adapter but not this one

**Comment by haydenmeade** [comment]
Seems to work for me, can you still repro? If so, do you have some more details about your setup (jest config, test file, etc)?

**Comment by dahmc** [comment]
@haydenmeade Great, it now all works. Thank you!
